Fix missing CSS
After upgrading to Puma no css was served.
Error messages like this occured:

    ... <NoMethodError: undefined method `silence' for #<Logger ...

I had to change the Logger to get CSS files from Puma.